# Generated by Django 4.1 on 2023-12-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='census',
            options={'verbose_name': 'Census', 'verbose_name_plural': 'Census'},
        ),
        migrations.AlterField(
            model_name='census',
            name='voter_id',
            field=models.PositiveIntegerField(verbose_name='Voter ID'),
        ),
        migrations.AlterField(
            model_name='census',
            name='voting_id',
            field=models.PositiveIntegerField(verbose_name='Voting ID'),
        ),
    ]
