# Generated by Django 4.1 on 2023-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='types',
            field=models.CharField(choices=[('OQ', 'Optional Question'), ('YN', 'Yes/No Question')], default='YN', max_length=2),
        ),
    ]
