# Generated by Django 4.1 on 2023-12-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_auth_options_alter_auth_me_alter_auth_name'),
        ('voting', '0005_question_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'verbose_name': 'Question Option', 'verbose_name_plural': 'Question Options'},
        ),
        migrations.AlterModelOptions(
            name='voting',
            options={'verbose_name': 'Voting', 'verbose_name_plural': 'Votings'},
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='types',
            field=models.CharField(choices=[('OQ', 'Optional Question'), ('YN', 'Yes/No Question')], default='YN', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='auths',
            field=models.ManyToManyField(related_name='votings', to='base.auth', verbose_name='Auths'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='pub_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting', to='base.key', verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='tally',
            field=models.JSONField(blank=True, null=True, verbose_name='Tally'),
        ),
    ]
