# Generated by Django 4.1 on 2023-12-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_question_options_alter_questionoption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voteBlank',
            field=models.BooleanField(default=False, verbose_name='Vote Blank'),
        ),
    ]
