# Generated by Django 4.1 on 2023-12-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_question_voteblank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='voteBlank',
            new_name='vote_blank',
        ),
    ]
