# Generated by Django 4.1 on 2023-12-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180921_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth',
            options={'verbose_name': 'Auth', 'verbose_name_plural': 'Auths'},
        ),
        migrations.AlterField(
            model_name='auth',
            name='me',
            field=models.BooleanField(default=False, verbose_name='Me'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
