# Generated by Django 4.1 on 2023-12-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_auth_options_alter_auth_me_alter_auth_name'),
        ('mixnet', '0004_auto_20180605_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mixnet',
            options={'verbose_name': 'Mixnet', 'verbose_name_plural': 'Mixnets'},
        ),
        migrations.AlterField(
            model_name='mixnet',
            name='auth_position',
            field=models.PositiveIntegerField(default=0, verbose_name='Auth Position'),
        ),
        migrations.AlterField(
            model_name='mixnet',
            name='auths',
            field=models.ManyToManyField(related_name='mixnets', to='base.auth', verbose_name='Auths'),
        ),
        migrations.AlterField(
            model_name='mixnet',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixnets', to='base.key', verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='mixnet',
            name='pubkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixnets_pub', to='base.key', verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='mixnet',
            name='voting_id',
            field=models.PositiveIntegerField(verbose_name='Voting ID'),
        ),
    ]
