# Generated by Django 4.1 on 2023-12-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_id',
            field=models.PositiveIntegerField(verbose_name='Voter ID'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voting_id',
            field=models.PositiveIntegerField(verbose_name='Voting ID'),
        ),
    ]
